<?php

return [
    require_once(__DIR__ . '/../../common/config/functions.php'),
    require_once(__DIR__ . '/../../common/config/languages.php'),
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'senderEmail' => 'noreply@example.com',
    'senderName' => 'Example.com mailer',
    'closeRobots' => 'yes',
    'searchBrand' => 'Бренд',
    'novaposhtaApiKey' => '0d06d56dd054bd4c639ea3dc058fe17f',
    'google_client_id'=>'657494972448-21en5ef4jh8ra4cbv4s1sfps13vv59mb.apps.googleusercontent.com',
    'google_client_secret'=>'3LW6TCCyco1FtGo1PMteitjF',
    'facebook_client_id'=>'337905196702866',
    'facebook_client_secret'=>'18262ae5dc763a211334a71d6392bcae',
    'liqpay_public_key'=>'i25036068535',
    'liqpay_private_key'=>'trl2RlGih4s7YtShxhTFJ0xW0m5sC3fJYYVKCwQD',
    'liqpay_result_url' => 'cart/thanks',
    'liqpay_server_url' => 'Куда придет ответ об оплате',
    'user.passwordResetTokenExpire' => 3600,
    'bsDependencyEnabled' => false,
    'sourceLanguage' => 'ru',
    'shopTitle' => 'Магазин | ',
    'languages' => get_languages(),
    'AccessControlRulesClose' => [
        'adminPanel',
        'calculator',
        'languages',
        'yandex',
        'yandex-news',
        'yandex-news-list',
        'video',
        'category',
        'product',
        'search-session',
        'stock',
        'shop',
        'size',
        'logout',
        'login',
        'error',
        '_form',
        '_search',
        'create',
        'index',
        'update',
        'view'
    ],
    'AccessControlRulesOpen' => [
        'logout',
        'login',
        'error',
    ],
];

